/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Default;

//File handling
//To connect to databse
import java.sql.Connection;
//Load Database Drivers
import java.sql.DriverManager;
//Statement
import java.sql.Statement;
//SQL Exceptions
import java.sql.SQLException;
//Prepared Statement
//ResultSet
import java.sql.ResultSet;
//Selecting a File
//For UI
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author pc
 */
public class FileBackup extends javax.swing.JInternalFrame {


    /**
     * Creates new form Cryptography
     */
    public FileBackup() {
        initComponents();
        CreateDatabaseAndTable();
       
    }
    
    private void CreateDatabaseAndTable() {
        String SQLURL = "jdbc:mysql://localhost:3307/";  // Adjust the URL for your database system
        String Username = "root";
        String Password = "kronosphereTSM";
        String DatabaseName = "Kronosphere";
        Connection connection = null;

        try {
            connection = DriverManager.getConnection(SQLURL, Username, Password);
            Statement statement = connection.createStatement();

            // Create the database if it doesn't exist
            statement.executeUpdate("CREATE DATABASE IF NOT EXISTS " + DatabaseName);

            // Switch to the new database
            statement.executeUpdate("USE " + DatabaseName);

            // Create the "Backup_Files" table
            String CreateTableSQL = "CREATE TABLE IF NOT EXISTS Backup_Files (" +
                    "ID INT AUTO_INCREMENT PRIMARY KEY," +
                    "File_Name VARCHAR(255) NOT NULL," +
                    "File_Size BIGINT NOT NULL," +
                    "File_Content LONGBLOB NOT NULL," +
                    "Date TIMESTAMP DEFAULT CURRENT_TIMESTAMP)";
            statement.executeUpdate(CreateTableSQL);

            System.out.println("Database and table created successfully.");
        } catch (SQLException ex) {
            System.err.println("Error creating the database and table: " + ex.getMessage());
        } finally {
            if (connection != null) {
                try {
                    connection.close();
                } catch (SQLException e) {
                    e.printStackTrace();
                }
            }
        }
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Retrieve1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        BackupTable = new javax.swing.JTable();

        setBorder(null);
        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(738, 477));

        Retrieve1.setBackground(new java.awt.Color(0, 153, 153));
        Retrieve1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 16)); // NOI18N
        Retrieve1.setForeground(new java.awt.Color(255, 255, 255));
        Retrieve1.setText("Show Backup Files");
        Retrieve1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        Retrieve1.setBorderPainted(false);
        Retrieve1.setMaximumSize(new java.awt.Dimension(146, 27));
        Retrieve1.setMinimumSize(new java.awt.Dimension(146, 27));
        Retrieve1.setPreferredSize(new java.awt.Dimension(146, 27));
        Retrieve1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Retrieve1ActionPerformed(evt);
            }
        });

        BackupTable.setBackground(new java.awt.Color(102, 102, 102));
        BackupTable.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        BackupTable.setForeground(new java.awt.Color(255, 255, 255));
        BackupTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(BackupTable);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 712, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Retrieve1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Retrieve1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 724, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 487, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Retrieve1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Retrieve1ActionPerformed
   String SQLURL = "jdbc:mysql://localhost:3307/Kronosphere";
    String Username = "root";
    String Password = "kronosphereTSM";
    Connection connection = null;
    DefaultTableModel model = (DefaultTableModel) BackupTable.getModel();
    model.setRowCount(0); // Clear the existing table data
    model.setColumnIdentifiers(new Object[]{"File Name", "File Size", "Date Uploaded"}); // Set column titles

    BackupTable.getColumnModel().getColumn(0).setPreferredWidth(400); // File Name column wider
    BackupTable.getColumnModel().getColumn(1).setPreferredWidth(80); // File Size column smaller
    BackupTable.getColumnModel().getColumn(2).setPreferredWidth(100); // Date column width

    try {
        connection = DriverManager.getConnection(SQLURL, Username, Password);
        Statement statement = connection.createStatement();
        ResultSet rs = statement.executeQuery("SELECT * FROM Backup_Files");

        while (rs.next()) {
            String fileName = rs.getString("File_Name");
            long fileSizeInBytes = rs.getLong("File_Size");
            String date = rs.getString("Date");

            // Format file size
            String formattedSize = formatFileSize(fileSizeInBytes);

            // Add retrieved data to the table model
            model.addRow(new Object[]{fileName, formattedSize, date});
        }
    } catch (SQLException ex) {
        System.err.println("Error retrieving data: " + ex.getMessage());
    } finally {
        if (connection != null) {
            try {
                connection.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }
    }//GEN-LAST:event_Retrieve1ActionPerformed
private String formatFileSize(long bytes) {
    final long kiloBytes = 1024;
    final long megaBytes = kiloBytes * 1024;
    final long gigaBytes = megaBytes * 1024;

    if (bytes < kiloBytes) {
        return bytes + " B";
    } else if (bytes < megaBytes) {
        return String.format("%.2f KB", (double) bytes / kiloBytes);
    } else if (bytes < gigaBytes) {
        return String.format("%.2f MB", (double) bytes / megaBytes);
    } else {
        return String.format("%.2f GB", (double) bytes / gigaBytes);
    }
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable BackupTable;
    private javax.swing.JButton Retrieve1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
