/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package Default;
import java.io.File;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.StandardCopyOption;
import java.sql.*;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;

//For UI

/**
 *
 * @author pc
 */
public class FileBin extends javax.swing.JInternalFrame {
public FileBin() { 
    initComponents(); 
    displayRecycleBinContents();
    startAutoRefresh();
    
}
    private void displayRecycleBinContents() {
    // JDBC connection parameters
     String url = "jdbc:mysql://localhost:3307/Kronosphere"; // Update URL with your database details
    String username = "root";
    String password = "kronosphereTSM";

    try (Connection connection = DriverManager.getConnection(url, username, password)) {
        // Query to retrieve data from recyclebin table
                createRecycleBinTable(connection);

        String sql = "SELECT file_name, file_path, deletion_date FROM recyclebin";
        
        try (Statement statement = connection.createStatement();
             ResultSet resultSet = statement.executeQuery(sql)) {

            // Create table model to store data for JTable
            DefaultTableModel model = new DefaultTableModel();
            model.setColumnIdentifiers(new Object[]{"File Name", "File Path", "Deletion Date"});

            // Loop through the result set and populate the table model
            while (resultSet.next()) {
                String fileName = resultSet.getString("file_name");
                String filePath = resultSet.getString("file_path");
                Timestamp deletionDate = resultSet.getTimestamp("deletion_date");

                // Add data to the table model
                model.addRow(new Object[]{fileName, filePath, deletionDate});
            }

            // Set the model to the jTable1
            FileBin.setModel(model);
        }
    } catch (SQLException e) {
        e.printStackTrace();
        // Handle database connection issues or SQL errors
    }
}
    private void createRecycleBinTable(Connection connection) throws SQLException {
    // SQL statement to create recyclebin table if it doesn't exist
    String createTableSQL = "CREATE TABLE IF NOT EXISTS recyclebin (id INT AUTO_INCREMENT PRIMARY KEY, file_name VARCHAR(255), file_path VARCHAR(1000), deletion_date TIMESTAMP)";

    try (Statement statement = connection.createStatement()) {
        // Execute the SQL statement to create the table
        statement.execute(createTableSQL);
    }
}
    private void startAutoRefresh() {
        int refreshInterval = 7000; // Refresh interval in milliseconds (e.g., every 7 seconds)
        Timer timer = new Timer(refreshInterval, e -> {
            displayRecycleBinContents(); // Refresh table contents
        });
        timer.start();
    }
   // Method to remove the file entry from the Recycle Bin database
private void removeFromRecycleBinDatabase(String fileName) {
     String url = "jdbc:mysql://localhost:3307/Kronosphere"; // Update URL with your database details
    String username = "root";
    String password = "kronosphereTSM";

    try (Connection connection = DriverManager.getConnection(url, username, password)) {
        Statement statement = connection.createStatement();

        // Execute a SQL DELETE query to remove the file entry
        String deleteQuery = "DELETE FROM recyclebin WHERE file_name = '" + fileName + "'";
        statement.executeUpdate(deleteQuery);

        System.out.println("File removed from Recycle Bin database.");
        
        // Close resources
        statement.close();
        connection.close();
    } catch (SQLException ex) {
        System.err.println("Error removing file from Recycle Bin database: " + ex.getMessage());
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Restore = new javax.swing.JButton();
        Shred1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        FileBin = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setIconifiable(true);
        setResizable(true);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setPreferredSize(new java.awt.Dimension(738, 477));

        Restore.setBackground(new java.awt.Color(0, 153, 153));
        Restore.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        Restore.setForeground(new java.awt.Color(255, 255, 255));
        Restore.setText("Restore");
        Restore.setBorder(null);
        Restore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestoreActionPerformed(evt);
            }
        });

        Shred1.setBackground(new java.awt.Color(255, 51, 51));
        Shred1.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 18)); // NOI18N
        Shred1.setForeground(new java.awt.Color(255, 255, 255));
        Shred1.setText("Shred");
        Shred1.setBorder(null);
        Shred1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Shred1ActionPerformed(evt);
            }
        });

        FileBin.setBackground(new java.awt.Color(102, 102, 102));
        FileBin.setFont(new java.awt.Font("Yu Gothic UI Semibold", 0, 14)); // NOI18N
        FileBin.setForeground(new java.awt.Color(255, 255, 255));
        FileBin.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(FileBin);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 703, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Restore, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Shred1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 430, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Restore, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addComponent(Shred1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 478, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RestoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestoreActionPerformed
    int selectedRow = FileBin.getSelectedRow(); // Get the index of the selected row in the Recycle Bin table

        if (selectedRow != -1) { // Ensure a row is selected in the Recycle Bin table
            String fileName = (String) FileBin.getValueAt(selectedRow, 0); // Assuming file name is in the first column

            // Get the project directory path
            String projectDirectory = System.getProperty("user.dir");

            // Create a directory for restored files within the Kronosphere folder in the project directory
            String kronospherePath = projectDirectory + "/Kronosphere";
            String restoredInKronospherePath = kronospherePath + "/Restored Files";

            // Create the "Restored Files" directory if it doesn't exist within the Kronosphere folder
            File restoredInKronosphereDirectory = new File(restoredInKronospherePath);
            if (!restoredInKronosphereDirectory.exists()) {
                boolean created = restoredInKronosphereDirectory.mkdirs();
                if (!created) {
                    System.err.println("Failed to create Restored Files folder in Kronosphere.");
                    return;
                }
            }

            // Get the path to the file in the Recycle Bin within the Kronosphere folder
            String recycleBinPath = kronospherePath + "/Recycle Bin";
            File fileInRecycleBin = new File(recycleBinPath + "/" + fileName);

            // Move the file from Recycle Bin to the "Restored Files" in Kronosphere
            File restoredFileLocation = new File(restoredInKronospherePath + "/" + fileName);

            try {
                Files.move(fileInRecycleBin.toPath(), restoredFileLocation.toPath(), StandardCopyOption.REPLACE_EXISTING);
                System.out.println("File restored successfully.");

                // Remove the file from the Recycle Bin database
                removeFromRecycleBinDatabase(fileName);
            } catch (IOException ex) {
                System.err.println("Error restoring file: " + ex.getMessage());
            }
        }
    }//GEN-LAST:event_RestoreActionPerformed

    private void Shred1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Shred1ActionPerformed
          int selectedRow = FileBin.getSelectedRow(); // Get the index of the selected row in the Recycle Bin table

    if (selectedRow != -1) { // Ensure a row is selected in the Recycle Bin table
        String fileName = (String) FileBin.getValueAt(selectedRow, 0); // Assuming file name is in the first column

        String projectDirectory = System.getProperty("user.dir");
        String kronospherePath = projectDirectory + "/Kronosphere";

        // Create a path to the Recycle Bin folder inside Kronosphere
        String recycleBinPath = kronospherePath + "/Recycle Bin";
        String filePathInRecycleBin = recycleBinPath + "/" + fileName;

        // Create a File object for the file in the Recycle Bin
        File fileToDelete = new File(filePathInRecycleBin);

        try {
            // Permanently delete the file
            Files.deleteIfExists(fileToDelete.toPath());
            System.out.println("File permanently shredded.");

            // Remove the file from the Recycle Bin database
            removeFromRecycleBinDatabase(fileName); // Assuming this method removes the file from the database

            // Update the table after shredding (remove the row)
            DefaultTableModel model = (DefaultTableModel) FileBin.getModel();
            model.removeRow(selectedRow);

            // Show a dialog confirming successful file shredding
            JOptionPane.showMessageDialog(null, "File permanently shredded.", "File Shredded", JOptionPane.INFORMATION_MESSAGE);
        } catch (IOException ex) {
            System.err.println("Error shredding file: " + ex.getMessage());
        }
    } else {
        System.out.println("Please select a file to shred from the Recycle Bin.");
    }
    }//GEN-LAST:event_Shred1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable FileBin;
    private javax.swing.JButton Restore;
    private javax.swing.JButton Shred1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
